site_name: oh, 2d maters

site_url: https://hao-ou.github.io/oh.2dmater.github.io/

plugins:
  - search

theme: 
  name: material
  logo: assets/Logo.png
  language: en
  palette: 
    primary: white
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
  font:
    text: Arial
    code: Roboto Mono

extra_css: 
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - footnotes

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Updates: News&history.md
  - CV: cv.md
  - Personal: personal.md
